### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mlucool** [dfcreative/mumath#2]
Hi,

The license file and pacakge.json license are not aligned:
https://github.com/dfcreative/mumath/blob/master/package.json#L18
https://github.com/dfcreative/mumath/blob/master/UNLICENSE

Per: https://docs.npmjs.com/files/package.json#license:
```
Finally, if you do not wish to grant others the right to use a private or unpublished package under any terms:

{ "license": "UNLICENSED"}
Consider also setting "private": true to prevent accidental publication.
```

Can you please update the package.json to be unlicense as that seems like the intent?

**Comment by dfcreative** [comment]
Done, thx!
